# Generated by Django 5.2.7 on 2025-10-30 05:48

import apps.core.utils.defaults
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.CharField(default=apps.core.utils.defaults.uuid_factory, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('host', models.URLField(blank=True, null=True)),
                ('service_name', models.CharField(max_length=100)),
                ('secret', models.CharField(db_index=True, default=apps.core.utils.defaults.uuid_factory, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
