# Generated by Django 5.2.7 on 2025-10-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_customuser_is_active_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('USER', 'User'), ('ADMIN', 'Admin')], default='USER', max_length=30, null=True),
        ),
    ]
